services:
  postgres:
    image: 'postgres:latest'
    container_name: 'main-database'
    environment:
      - POSTGRES_DB=summit-store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    networks:
      - 'app-network'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 2s
  minio:
    image: 'minio/minio:latest'
    container_name: 'main-storage'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    ports:
      - '9000:9000' # MinIO API
      - '9001:9001' # MinIO Console
    volumes:
      - 'minio-data:/data'
    networks:
      - 'app-network'
    command: 'minio server /data --console-address ":9001"'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live' ]
      interval: 2s

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local

networks:
  app-network:
    driver: bridge