CREATE TABLE brand
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(100)                             NOT NULL,
    description   VARCHAR(1000)                            NOT NULL,
    brand_logo_id VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_brand PRIMARY KEY (id),
    CONSTRAINT uc_brand_name UNIQUE (name),
    CONSTRAINT uc_brand_logo_id UNIQUE (brand_logo_id),
    CONSTRAINT FK_BRAND_ON_IMAGE FOREIGN KEY (brand_logo_id) REFERENCES image (file_name)
);